[workspace]
authors = ["Syver Døving Agdestein <syverda@gmail.com>"]
channels = ["conda-forge"]
name = "FlowMatching"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pytorch = ">=2.7.1,<3"
matplotlib = ">=3.10.5,<4"
torchvision = ">=0.22.0,<0.23"
ipykernel = ">=6.30.1,<7"
tqdm = ">=4.67.1,<5"
seaborn = ">=0.13.2,<0.14"
celluloid = ">=0.2.0,<0.3"
scikit-learn = ">=1.7.1,<2"
